/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CoverLettersRouteImport } from './routes/cover-letters'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRoute = CoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career': typeof CareerRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career': typeof CareerRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs': typeof JobsIndexRoute
  '/resumes': typeof ResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career': typeof CareerRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/career'
    | '/cover-letters'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs/'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/career'
    | '/cover-letters'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs'
    | '/resumes'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/career'
    | '/cover-letters'
    | '/dashboard'
    | '/login'
    | '/sitemap.xml'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs/'
    | '/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CareerRoute: typeof CareerRoute
  CoverLettersRoute: typeof CoverLettersRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CareerRoute: CareerRoute,
  CoverLettersRoute: CoverLettersRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
