# Generated by Django 6.0.7 on 2026-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
