# Generated by Django 6.0.7 on 2026-07-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeversion_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeversion',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
