# Generated by Django 6.0.7 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resumeversion_pdf_file_resumeversion_pdf_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='generation_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='generation_status',
            field=models.CharField(default='idle', max_length=255),
        ),
    ]
