# Generated by Django 6.0.7 on 2026-07-09 01:16

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('project', 'Project'), ('experience', 'Experience'), ('education', 'Education'), ('achievement', 'Achievement'), ('certification', 'Certification'), ('award', 'Award'), ('leadership', 'Leadership'), ('publication', 'Publication')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('duration_start', models.DateField(blank=True, null=True)),
                ('duration_end', models.DateField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(default='bge-small-en-v1.5', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-duration_start'],
            },
        ),
    ]
