# Generated by Django 6.0.7 on 2026-07-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerentry',
            options={'ordering': ['-duration_start'], 'verbose_name': 'career entry', 'verbose_name_plural': 'career entries'},
        ),
    ]
